services:
  db:
    image: postgres:17
    volumes:
      - ./postgres_data_tf:/var/lib/postgresql/data
    env_file:
      - .env.prod

  django-web:
    build: .
    user: appuser:appuser
    container_name: django-docker
    depends_on:
      - db
    volumes:
      - ./static:/tmp/static
      - static_volume:/app/staticfiles
    env_file:
      - .env.prod

  frontend-proxy:
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/static:ro
    depends_on:
      - django-web
volumes:
  postgres_data_tf:
  static_volume:
