# Generated by Django 5.1.7 on 2025-06-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=256)),
                ('processing_time', models.FloatField()),
                ('processed_timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('error', 'Error'), ('success', 'Success')])),
                ('memory_usage', models.FloatField()),
            ],
            options={
                'ordering': ['-processed_timestamp'],
                'indexes': [models.Index(fields=['processed_timestamp'], name='tfidf_app_m_process_13caa5_idx')],
            },
        ),
    ]
